version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  db-test:
    container_name: db-test
    image: postgres:15-alpine
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  api:
    container_name: api
    image: golang:1.20-alpine
    working_dir: /app/cmd/api
    command: /bin/sh /app/start.sh
    volumes:
      - .:/app
      - go_cache:/go/pkg
    environment:
      - GOCACHE=/go/pkg
    ports:
      - "7070:8080"
    depends_on:
      - db
      - db-test

volumes:
  postgres_data:
  go_cache: